logging:
  level:
    root: WARN
    org.dddjava.jig: INFO

jig:
  # Output targets (multiple specifications with commas)
  #document:
  #  types: PackageSummary,BusinessRuleList
  output:
    directory: ./build/jig
  # Domain class pattern (regular expression)
  #pattern:
  #  domain: .+\.domain\.(model|type)\..+

# Root directory to read information
project:
  path: ./

# Directories to read information
#directory:
#  classes: build/classes/java/main
#  resources: build/resources/main
#  sources: src/main/java
