logging:
  level:
    root: WARN
    org.dddjava.jig: INFO

jig:
  # Output targets (multiple specifications with commas)
  #document:
  #  types: ServiceMethodCallHierarchyDiagram,PackageRelationDiagram,BusinessRuleList
  output:
    directory: ./build/jig
    diagram:
      format: svg
  # Domain class pattern (regular expression)
  #pattern:
  #  domain: .+\.domain\.(model|type)\..+

# Root directory to read information
project:
  path: ./

# Directories to read information (Gradle standard)
directory:
  classes: build/classes/java/main
  resources: build/resources/main
  sources: src/main/java