version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: ".github/workflows"
  schedule:
    interval: daily
    time: "07:00"
