version: 2
anchors:
  usually-build: &usually-build
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont
    - restore_cache:
        key: gradle-dependencies-{{ checksum "build.gradle" }}
    - run: ./gradlew build
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-dependencies-{{ checksum "build.gradle" }}
    - store_test_results:
        path: jig-core/build/test-results
jobs:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    <<: *usually-build
  java-10:
    docker:
    - image: circleci/openjdk:10-jdk
    <<: *usually-build

  release-build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y graphviz fonts-ipafont
      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew build
      - store_test_results:
          path: jig-core/build/test-results

      # RELEASE
      - store_artifacts:
          path: jig-cli/build/libs
          destination: module
      - run: |
         java -jar jig-cli/build/libs/jig-cli.jar --outputDirectory=example
      - store_artifacts:
          path: example
          destination: example
      - run: ./gradlew :jig-annotation:bintrayUpload :jig-core:bintrayUpload :jig-gradle-plugin:publishPlugins
workflows:
  version: 2
  usually:
    jobs:
      - java-8
      - java-10
  release:
    jobs:
      - release-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/

