name: Main Upkeep

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java-version: [ '21' ]
    name: build Java ${{ matrix.java-version }} (${{ matrix.os }})
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dfile.encoding=UTF-8'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Set UTF-8 encoding for Windows
        if: runner.os == 'Windows'
        run: chcp.com 65001
      - name: Run Build
        run: |
          ./gradlew build --continue
      - name: Upload test failure report
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-failure-reports-${{ matrix.java-version }}-${{ runner.os }}
          path: build/reports/tests/
          retention-days: 3

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build classes
        run: ./gradlew build -x test
      - name: Download latest JIG CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download --pattern jig-cli.jar
      - name: Run JIG
        run: java -jar jig-cli.jar
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/jig
