# DependabotからのPRをauto mergeとマークする
# githubのドキュメントに記載されているものを調整（metadata取得などを除外）
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
# リポジトリでは branch protection を設定し、PRに対する検証は他のActionで行う。

name: Dependabot auto-merge
on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'dddjava/jig'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # PATで指定しないとmainにmergeはされるが、mergeした時のworkflowが動かない。
          GH_TOKEN: ${{secrets.DEPENDABOT_AUTO_MERGE_PAT}}

