name: Test & Merge PR

on:
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Build with Tests
        run: ./gradlew build
      - name: Merge Pull Request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
      - name: Upload Failure Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-failure-reports
          path: jig-*/build/reports/tests/
          retention-days: 3
